### ISSUE TITLE
2.0.3 caused Module build failed: TypeError: fn.apply is not a function

### ISSUE THREAD

**Issue by zincli** [shakacode/sass-resources-loader#115]
2.0.3 caused errors.
2.0.1 works fine.

Module build failed: TypeError: fn.apply is not a function
        at applySyncOrAsync (/cloud/source_code/node_modules/_happypack@3.1.0@happypack/lib/applyLoaders.js:342:21)
        at apply (/cloud/source_code/node_modules/_happypack@3.1.0@happypack/lib/applyLoaders.js:269:5)
        at /cloud/source_code/node_modules/_happypack@3.1.0@happypack/lib/applyLoaders.js:132:7
        at applyPitchLoader (/cloud/source_code/node_modules/_happypack@3.1.0@happypack/lib/applyLoaders.js:185:14)
        at applyPitchLoader (/cloud/source_code/node_modules/_happypack@3.1.0@happypack/lib/applyLoaders.js:193:14)
        at applyPitchLoader (/cloud/source_code/node_modules/_happypack@3.1.0@happypack/lib/applyLoaders.js:193:14)
        at applyPitchLoader (/cloud/source_code/node_modules/_happypack@3.1.0@happypack/lib/applyLoaders.js:193:14)
        at applyPitchLoader (/cloud/source_code/node_modules/_happypack@3.1.0@happypack/lib/applyLoaders.js:193:14)
        at applyPitchLoaders (/cloud/source_code/node_modules/_happypack@3.1.0@happypack/lib/applyLoaders.js:223:4)
        at applyLoaders (/cloud/source_code/node_modules/_happypack@3.1.0@happypack/lib/applyLoaders.js:117:3

**Comment by justin808** [comment]
@zincli can you try 2.0.2?

**Comment by justin808** [comment]
@zincli do you have a reproduction case?
