### ISSUE TITLE
 Module build failed: File to import not found or unreadable: css3/border-radius

### ISSUE THREAD

**Issue by wzup** [shakacode/sass-resources-loader#14]
Looks like the plugin can't resolve `@include`s within mixins, can it?

Here is a use case and the error.
For `sassResources` I want to use [compass-mixins](https://github.com/Igosuki/compass-mixins) module. It has all mixins that I need in `.scss`. And its mixin files include other files a lot. For example, this entry point for `css3` mixins looks like this: `node_modules\compass-mixins\lib\compass\_css3.scss`:

```
@import "css3/border-radius";
@import "css3/inline-block";
@import "css3/opacity";
@import "css3/box-shadow";
@import "css3/text-shadow";
@import "css3/columns";
@import "css3/box-sizing";
... and so on ...
```

Then the very first `css3/border-radius` mixin file looks like this, pay attention that it imports other `shared` file:
```
@import "shared";

$default-border-radius: 5px !default;

// Round all corners by a specific amount, defaults to value of `$default-border-radius`.
... so on...
```

So the most logical and the best approach is to specify just an entry point for `sassResources`, isn't it?
```
sassResources: ['./node_modules/compass-mixins/lib/compass/_css3.scss'],
```

But it is not the case with you plugin. It throws an error. My question. Can the plugin resolve all natural `@include`s that happen in mixin files? Or it expects pure `css` mixins only without any `@include` statements and other nice features? Like in your primitive example
```
$section-width: 700px;

@mixin section-mixin {
  margin: 0 auto;
  width: $section-width;
}
```

The error. I inclde `./assets/sass/_styles.scss` into one of my react components:
```
require('./assets/sass/_styles.scss');
```

My webpack settings:
```
{
    test: /\.scss$/i,
    loader: ExtractTextPlugin.extract('css?modules&importLoaders=1&-minimize&localIdentName=[local]_[hash:3]!sass!sass-resources')
},
sassResources: ['./node_modules/compass-mixins/lib/compass/_css3.scss'],
```

The error thrown:
```
ERROR in ./assets/sass/_styles.scss
Module build failed: ModuleBuildError: Module build failed:
.div_class_a, .div_class_b {
^
      File to import not found or unreadable: css3/border-radius
Parent style sheet: stdin
      in C:\Users\user\app\assets\sass\_styles.scss (line 1, column 1)
    at DependenciesBlock.onModuleBuildFailed (C:\Users\user\app\node_modules\webpack-core\lib\NormalModuleMixin.js:315:19)
    at nextLoader (C:\Users\user\app\node_modules\webpack-core\lib\NormalModuleMixin.js:270:31)
    at C:\Users\user\app\node_modules\webpack-core\lib\NormalModuleMixin.js:292:15
    at context.callback (C:\Users\user\app\node_modules\webpack-core\lib\NormalModuleMixin.js:148:14)
    at Object.onRender (C:\Users\user\app\node_modules\sass-loader\index.js:272:13)
    at C:\Users\user\app\node_modules\async\lib\async.js:906:35
    at _arrayEach (C:\Users\user\app\node_modules\async\lib\async.js:85:13)
    at Object.<anonymous> (C:\Users\user\app\node_modules\async\lib\async.js:898:17)
    at Object.callback (C:\Users\user\app\node_modules\async\lib\async.js:44:16)
    at options.error (C:\Users\user\app\node_modules\node-sass\lib\index.js:295:32)
 @ ./assets/js/react/dev/MyReactComponent.js 32:0-53
Child extract-text-webpack-plugin:

    ERROR in ./~/css-loader?modules&importLoaders=1&-minimize&localIdentName=[local]_[hash:3]!./~/sass-loader!./~/sass-resources-loader/lib/loader.js!./assets/sass/_styles.scss
    Module build failed:
    .div_class_a, .div_class_b {
    ^
          File to import not found or unreadable: css3/border-radius
    Parent style sheet: stdin
          in C:\Users\user\app\assets\sass\_styles.scss (line 1, column 1)
    Error:
    .div_class_a, .div_class_b {
    ^
          File to import not found or unreadable: css3/border-radius
    Parent style sheet: stdin
          in C:\Users\user\app\assets\sass\_styles.scss (line 1, column 1)
        at options.error (C:\Users\user\app\node_modules\node-sass\lib\index.js:292:26)
```

**Comment by wzup** [comment]
The issue in not new. Here is the beginning of the the discussion. And as for this time it is not solved
https://github.com/shakacode/sass-resources-loader/issues/6
