### ISSUE TITLE
Builds are failing with "if (single.indexOf('sass:') === 0) {"

### ISSUE THREAD

**Issue by MichaelPolonsky** [shakacode/sass-resources-loader#143]
Builds are failing with the following message

 "sass-resources-loader": "^2.2.1",
  "webpack": "~4.44.2",
  "sass-loader": "^10.1.1",
  "node-sass": "^4.11.0",

`Compiling with '/opt/atlassian/pipelines/agent/build/webclient' as base path.
Build environment 'production'.
/opt/atlassian/pipelines/agent/build/webclient/node_modules/sass-resources-loader/lib/utils/rewritePaths.js:41
    if (single.indexOf('sass:') === 0) {
               ^
TypeError: Cannot read property 'indexOf' of undefined
    at /opt/atlassian/pipelines/agent/build/webclient/node_modules/sass-resources-loader/lib/utils/rewritePaths.js:41:16
    at String.replace (<anonymous>)
    at rewritePaths (/opt/atlassian/pipelines/agent/build/webclient/node_modules/sass-resources-loader/lib/utils/rewritePaths.js:39:28)
    at /opt/atlassian/pipelines/agent/build/webclient/node_modules/sass-resources-loader/lib/loader.js:73:36
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:73:3)`
    

Anything we can do to fix it?  
Downgrade?

**Comment by MichaelPolonsky** [comment]
Closing as duplicate of https://github.com/shakacode/sass-resources-loader/issues/144
