### ISSUE TITLE
Webpack 5 support for Angular 12

### ISSUE THREAD

**Issue by yackinn** [shakacode/sass-resources-loader#146]
Do you want to support Angular 12 and Webpack 5?

I'm seeing this error on Angular 12.0.3.
The builder is using webpack 5.38.1.

I'm using sass-resource-loader version 2.2.2

```bash
Generating browser application bundles (phase: building).... /node_modules/sass-resources-loader/lib/utils/rewritePaths.js:41
    if (single.indexOf('sass:') === 0) {
               ^

TypeError: Cannot read property 'indexOf' of undefined
    at /node_modules/sass-resources-loader/lib/utils/rewritePaths.js:41:16
    at String.replace (<anonymous>)
    at rewritePaths (/node_modules/sass-resources-loader/lib/utils/rewritePaths.js:39:28)
    at /node_modules/sass-resources-loader/lib/loader.js:73:36
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)

———————————————————————————————————————————————

>  NX   ERROR  Running target "ui:serve" failed
```

**Comment by yackinn** [comment]
The error is resolved by https://github.com/shakacode/sass-resources-loader/issues/144.

**Comment by nsunga** [comment]
Hey @yackinn 

Quick follow up on this.

So have you been using this package with webpack 5?

I just want to know if its compatible with v5 since theres no official notes or word for v5 support

**Comment by justin808** [comment]
Yes, it works with Webpack v5.
