### ISSUE TITLE
webpack2 + ExtractTextPlugin issues

### ISSUE THREAD

**Issue by BenDiuguid** [shakacode/sass-resources-loader#18]
Hey, so I have forked the repo and modified the example app to provide a reproduction for the error I'm receiving. Here is the link to the [repo's example/](https://github.com/BenDiuguid/sass-resources-loader/tree/alex/webpack-v2/example)

I have been looking at #16 and I cannot get this to work.

https://github.com/shakacode/sass-resources-loader/blob/alex/webpack-v2/src/loader.js#L29
Here, the call to `parseResources(...)` returns nothing, and I have been unable to determine why yet.

Let me know if there is anything I can do to help.

Thank you so much!

```
> sass-resources-loader-example@0.0.1 start /Users/benjamind/projects/sass-issues/my-sass-resources-loader/example
> nodemon --watch server.js server.js

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: server.js
[nodemon] starting `node server.js`
keywords if/then/else require v5 option
=> 🔥  Webpack dev server is running on port 4000
webpack built f16f5689c697e3e0ee9e in 2277ms
Time: 2277ms
 Asset     Size  Chunks  Chunk Names
app.js  2.53 MB       0  main

ERROR in ./app/layout/Layout.scss
Module build failed: ModuleBuildError: Module build failed: Error: 
      Something wrong with provided resources.
      Make sure 'options.resources' is String or Array of Strings.
    
    at Object.module.exports (/Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/sass-resources-loader/lib/loader.js:55:17)
    at /Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/webpack/lib/NormalModule.js:143:35
    at /Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/loader-runner/lib/LoaderRunner.js:359:11
    at /Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/loader-runner/lib/LoaderRunner.js:225:18
    at context.callback (/Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/loader-runner/lib/LoaderRunner.js:106:13)
    at Object.module.exports (/Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/sass-resources-loader/lib/loader.js:57:12)
 @ ./app/layout/Layout.jsx 33:14-38
 @ ./app/startup/App.jsx
 @ multi main

ERROR in ./app/components/Hero/Hero.scss
Module build failed: ModuleBuildError: Module build failed: Error: 
      Something wrong with provided resources.
      Make sure 'options.resources' is String or Array of Strings.
    
    at Object.module.exports (/Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/sass-resources-loader/lib/loader.js:55:17)
    at /Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/webpack/lib/NormalModule.js:143:35
    at /Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/loader-runner/lib/LoaderRunner.js:359:11
    at /Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/loader-runner/lib/LoaderRunner.js:225:18
    at context.callback (/Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/loader-runner/lib/LoaderRunner.js:106:13)
    at Object.module.exports (/Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/sass-resources-loader/lib/loader.js:57:12)
 @ ./app/components/Hero/Hero.jsx 25:12-34
 @ ./app/layout/Layout.jsx
 @ ./app/startup/App.jsx
 @ multi main

ERROR in ./app/components/Content/Content.scss
Module build failed: ModuleBuildError: Module build failed: Error: 
      Something wrong with provided resources.
      Make sure 'options.resources' is String or Array of Strings.
    
    at Object.module.exports (/Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/sass-resources-loader/lib/loader.js:55:17)
    at /Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/webpack/lib/NormalModule.js:143:35
    at /Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/loader-runner/lib/LoaderRunner.js:359:11
    at /Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/loader-runner/lib/LoaderRunner.js:225:18
    at context.callback (/Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/loader-runner/lib/LoaderRunner.js:106:13)
    at Object.module.exports (/Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/sass-resources-loader/lib/loader.js:57:12)
 @ ./app/components/Content/Content.jsx 25:15-40
 @ ./app/layout/Layout.jsx
 @ ./app/startup/App.jsx
 @ multi main

ERROR in ./app/layout/Layout.scss
Module build failed: ModuleBuildError: Module build failed: Error: 
      Something wrong with provided resources.
      Make sure 'options.resources' is String or Array of Strings.
    
    at Object.module.exports (/Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/sass-resources-loader/lib/loader.js:55:17)
    at /Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/webpack/lib/NormalModule.js:143:35
    at /Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/loader-runner/lib/LoaderRunner.js:359:11
    at /Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/loader-runner/lib/LoaderRunner.js:225:18
    at context.callback (/Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/loader-runner/lib/LoaderRunner.js:106:13)
    at Object.module.exports (/Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/sass-resources-loader/lib/loader.js:57:12)

ERROR in ./app/components/Content/Content.scss
Module build failed: ModuleBuildError: Module build failed: Error: 
      Something wrong with provided resources.
      Make sure 'options.resources' is String or Array of Strings.
    
    at Object.module.exports (/Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/sass-resources-loader/lib/loader.js:55:17)
    at /Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/webpack/lib/NormalModule.js:143:35
    at /Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/loader-runner/lib/LoaderRunner.js:359:11
    at /Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/loader-runner/lib/LoaderRunner.js:225:18
    at context.callback (/Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/loader-runner/lib/LoaderRunner.js:106:13)
    at Object.module.exports (/Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/sass-resources-loader/lib/loader.js:57:12)

ERROR in ./app/components/Hero/Hero.scss
Module build failed: ModuleBuildError: Module build failed: Error: 
      Something wrong with provided resources.
      Make sure 'options.resources' is String or Array of Strings.
    
    at Object.module.exports (/Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/sass-resources-loader/lib/loader.js:55:17)
    at /Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/webpack/lib/NormalModule.js:143:35
    at /Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/loader-runner/lib/LoaderRunner.js:359:11
    at /Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/loader-runner/lib/LoaderRunner.js:225:18
    at context.callback (/Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/loader-runner/lib/LoaderRunner.js:106:13)
    at Object.module.exports (/Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/sass-resources-loader/lib/loader.js:57:12)

ERROR in /Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/extract-text-webpack-plugin/loader.js?{"omit":0,"remove":true}!/Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/style-loader/index.js!/Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/css-loader/index.js!/Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/postcss-loader/index.js!/Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/sass-loader/index.js!/Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/sass-resources-loader/lib/loader.js!/Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/app/layout/Layout.scss doesn't export content

ERROR in /Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/extract-text-webpack-plugin/loader.js?{"omit":0,"remove":true}!/Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/style-loader/index.js!/Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/css-loader/index.js!/Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/postcss-loader/index.js!/Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/sass-loader/index.js!/Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/sass-resources-loader/lib/loader.js!/Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/app/components/Content/Content.scss doesn't export content

ERROR in /Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/extract-text-webpack-plugin/loader.js?{"omit":0,"remove":true}!/Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/style-loader/index.js!/Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/css-loader/index.js!/Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/postcss-loader/index.js!/Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/sass-loader/index.js!/Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/node_modules/sass-resources-loader/lib/loader.js!/Users/benjamind/projects/sass-issues/my-sass-resources-loader/example/app/components/Hero/Hero.scss doesn't export content
webpack: bundle is now VALID.
```

**Comment by alexfedoseev** [comment]
@BenDiuguid It might be related to [this issue](https://github.com/shakacode/sass-resources-loader/pull/16#discussion_r95525656). Also, I don't think [it's valid](https://github.com/BenDiuguid/sass-resources-loader/commit/8d830698fa39ce2e771e0e506e7427a4521e814d#diff-9bb3de20ef60fb0751fb0025b2cd27eaR28).

**Comment by alexfedoseev** [comment]
@BenDiuguid I published `1.2.0-beta.2`, try it out.
Also I added [example w/ `extract-text-webpack-plugin`](https://github.com/shakacode/sass-resources-loader/tree/alex/webpack-v2/example).
It works for me: 

<img width="1280" alt="screen shot 2017-01-23 at 18 07 29" src="https://cloud.githubusercontent.com/assets/4244251/22199989/24639e36-e198-11e6-9699-a6c067e67fdb.png">

**Comment by BenDiuguid** [comment]
Should [importLoaders: 2](https://github.com/shakacode/sass-resources-loader/blob/alex/webpack-v2/example/webpack.prod.config.js#L38) be `3`?

also shouldn't it be `options` instead of `query`? [From Migration guide](https://webpack.js.org/guides/migrating/#module-loaders-is-now-module-rules)

I believe that `query` works currently, (I have to solve some other issues now, but that shouldn't be too bad :) )

**Comment by BenDiuguid** [comment]
So after debugging a different issue, this may be a problem with ExtractTextPlugin, because it looks like ExtractTextPlugin does not relay the `options` currently.

i.e., I had to switch from options to query for css-loader: http://stackoverflow.com/questions/41021614/webpack-2-css-modules-support

**Comment by gilhanan** [comment]
@BenDiuguid can you show the correct syntax? thanks!

**Comment by BenDiuguid** [comment]
I have brought this up [here](https://github.com/webpack/extract-text-webpack-plugin/issues/353) So this is good to be closed 👍
